export enum UserActionType {
  USER_LOADED = 'USER_LOADED',
  LOG_IN = 'LOG_IN',
  LOG_IN_SUCCESS = 'LOG_IN_SUCCESS',
  LOG_IN_ERROR = 'LOG_IN_ERROR',

  LOG_OUT = 'LOG_OUT',
}

export enum ForumActionType {
  LOAD_FORUM_POSTS = 'LOAD_FORUM_POSTS',
  LOAD_FORUM_POSTS_SUCCESS = 'LOAD_FORUM_POSTS_SUCCESS',
  LOAD_FORUM_POSTS_ERROR = 'LOAD_FORUM_POSTS_ERROR',

  DELETE_FORUM_POST = 'DELETE_FORUM_POST',
  DELETE_FORUM_POST_SUCCESS = 'DELETE_FORUM_POST_SUCCESS',
  DELETE_FORUM_POST_ERROR = 'DELETE_FORUM_POSTERROR',

  ADD_LIKE_FORUM_POST = 'ADD_LIKE_FORUM_POST',
}
